### ISSUE TITLE
Consider multi module maven projects

### ISSUE THREAD

**Issue by Ingvord** [rcsb/devops-cicd-github-actions#12]
Turns out we do have a few multi module maven projects. There is a couple of ways to deal with them:

1) get rid off them
2) alter GitHub actions workflow to be aware of those

I would personally go with the first option, as frankly speaking maven multi module add very little value (if any), but introduces a lot of maintenance pain, for instance when one project produces mutiple artifacts. That simply violates the General rule of thumb - single artifact per repo

Second option requires some research...

**Comment by josemduarte** [comment]
Historically we've hit the multi-module project problem a few times and did have quite a few issues with it. For instance rcsb-mojave started as multi module and eventually was split up. So my vote is to try to avoid them if at all possible.

**Comment by JonStargaryen** [comment]
Can attest to the immense pain that multi-modules bring. I think it's only rcsb-strucmotif, which could be easily split or cleaned up.
