### ISSUE TITLE
A few warnings when running push2master

### ISSUE THREAD

**Issue by josemduarte** [rcsb/devops-cicd-github-actions#15]
When running push-to-master in rcsb-shape a few warnings came up, see https://github.com/rcsb/rcsb-shape/actions/runs/4199106580

@Ingvord could you have a look at resolving them?

**Comment by Ingvord** [comment]
Yes, that ones require changes in the rooting workflows to automatically extract version. It is on my to-do list

**Comment by henrychao-rcsb** [comment]
Closing out this issue, as we refactored the workflow syntax to use another common workflow file rather than branch specific ones.
