### ISSUE TITLE
Enable `concurrency`

### ISSUE THREAD

**Issue by Ingvord** [rcsb/devops-cicd-github-actions#16]
Following @JonStargaryen advice. 

It would be nice to automatically cancel currently running jobs, if a  new one has to start due to e.g. multiple fast sequential commits/pushes.

See [GHA concurrency](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency)

**Comment by Ingvord** [comment]
Looks like has been resolved via [8c83d8a](https://github.com/rcsb/devops-cicd-github-actions/commit/8c83d8aa35c91b8fbc4f0a0f9a2ec52f5d2a7980)

@JonStargaryen sorry for the racing

**Comment by JonStargaryen** [comment]
> sorry for the racing

Wait, there are good race conditions? :)
