### ISSUE TITLE
War bundle needs a different handling than tgz bundle for buildlocker upload

### ISSUE THREAD

**Issue by josemduarte** [rcsb/devops-cicd-github-actions#17]
Our war files are single all-in-one bundles. That means for the war case, we just need to upload the war file already produced by maven (see any of the old gitlab CI scripts).

I guess we are going to need an if condition somewhere here:

https://github.com/rcsb/devops-cicd-github-actions/blob/master/.github/workflows/deploy-to-buildloker.yaml#L27-L29

**Comment by Ingvord** [comment]
OK, this is now solved, see e.g. [arches](https://github.com/rcsb/rcsb-arches/actions/runs/4317506188/jobs/7534680495)

**Comment by josemduarte** [comment]
Very nice indeed, thanks!
